Checking to confirm that bit-blocks-starter directory exists on the runner

diff --git a/.github/workflows/cicd-validate.yml b/.github/workflows/cicd-validate.yml
--- a/.github/workflows/cicd-validate.yml
+++ b/.github/workflows/cicd-validate.yml
@@ -70,6 +70,18 @@ jobs:
 
       - name: 🔍 Lint GitLab CI templates
         run: |
+          ls ../bit-blocks-starter/
+          # Confirm the directory exists
+          if [ ! -d "../bit-blocks-starter/cicd-pipelines/gitlab/" ]; then
+            echo -e "\033[1;31m❌ Directory not found:\033[0m ../bit-blocks-starter/cicd-pipelines/gitlab/"
+            exit 1
+          fi
+
+          # Confirm there are files in the directory
+          if [ -z "$(ls -A ../bit-blocks-starter/cicd-pipelines/gitlab/*.yml 2>/dev/null)" ]; then
+            echo -e "\033[1;31m❌ No YAML files found in:\033[0m ../bit-blocks-starter/cicd-pipelines/gitlab/"
+            exit 1
+          fi
           cd gitlab-ci-lint
           for file in ../bit-blocks-starter/cicd-pipelines/gitlab/*.yml; do
           filename=$(basename "$file")
